name: Release

on:
  push:
    branches:
      - main

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - name: Check Patch Label
        id: check_pr_labels_patch
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["release:patch"]'

      - name: Check Minor Label
        id: check_pr_labels_minor
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["release:minor"]'

      - name: Check Major Label
        id: check_pr_labels_major
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["release:major"]'

      - name: Release Type
        run: |
          if [ ${MAJOR} == "true" ] ; then
            echo "RELEASE_TYPE=major" >> $GITHUB_ENV
          elif [ ${MINOR} == "true" ] ; then
            echo "RELEASE_TYPE=minor" >> $GITHUB_ENV
          else
          echo "RELEASE_TYPE=patch" >> $GITHUB_ENV
          fi
        env:
          MINOR: ${{ steps.check_pr_labels_minor.outputs.result }}
          MAJOR: ${{ steps.check_pr_labels_major.outputs.result }}

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ env.RELEASE_TYPE }}

      - name: Creating Github Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          generateReleaseNotes: true
          prerelease: false
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.changelog.outputs.changelog }}
